### ISSUE TITLE
writing_data_to_eth: remove `'let's`

### ISSUE THREAD

**Issue by nick1udwig** [kinode-dao/kinode-book#193]
https://github.com/kinode-dao/kinode-book/blob/main/src/cookbook/writing_data_to_eth.md

**Comment by nick1udwig** [comment]
The `we` and `let's` style is quite natural, so perhaps it is worth revisiting the global recommendation. I must say, it does hurt the academic in me to not be able to say "we", "let's".

**Comment by bitful-pannul** [comment]
I prefer we/let's too..

**Comment by nick1udwig** [comment]
https://github.com/kinode-dao/kinode-book/issues/195
