### ISSUE TITLE
clearly describe how to dev UI without relying on `build` for UI part

### ISSUE THREAD

**Issue by hosted-fornet** [kinode-dao/kinode-book#87]
The conversation kicked off here illustrates the need to have clear instructions for devs who are not opting in to nvm/npm/node:

https://discord.com/channels/1186394868336038080/1186421052071477428/1199804322507137065

E.g., see parts below:

https://discord.com/channels/1186394868336038080/1186421052071477428/1199807935941976226
https://discord.com/channels/1186394868336038080/1186421052071477428/1199808329791312023
https://discord.com/channels/1186394868336038080/1186421052071477428/1199808911503532192

FYI @0x70b1a5 @willbach do you have ideas here for where/how we can provide clear discussion of this?

**Comment by willbach** [comment]
#92 should be close to what we need. I'm not sure where to put it so I put it in `apis`
